version: '3'
services:
  app:
    env_file: .env
    volumes:
      - .:/data:cached
      - ~/.gitconfig:/root/.gitconfig
      - /var/run/docker.sock:/var/run/docker.sock 
    command: /bin/sh -c "while sleep 1000; do :; done"

